resolver: lts-13.5
extra-deps:
- net-mqtt-0.2.2.0
- twitter-types-0.7.2
- twitter-types-lens-0.7.2
- jwt-0.9.0
- servant-flatten-0.2
# - keycloak-hs-0.0.0.2
packages:
- '.'
- './aesonbson'
- './keycloak-hs'
- './orion-hs'
- './twitter-conduit'
allow-newer: true
