resolver: lts-13.5
extra-deps:
- net-mqtt-0.2.2.0
- twitter-types-0.9.0
- twitter-types-lens-0.9.0
- twitter-conduit-0.4.0
- jwt-0.10.0
- servant-flatten-0.2
- AesonBson-0.4.0
# - keycloak-hs-0.0.0.2
packages:
- '.'
- './keycloak-hs'
- './orion-hs'
- './haskell-cache'
allow-newer: true
