snapshot: lts-16.18
extra-deps:
- net-mqtt-0.7.0.1
- twitter-types-0.10.1
- twitter-types-lens-0.10.0
- twitter-conduit-0.5.0
- jwt-0.10.0
- servant-flatten-0.2
- servant-swagger-tags-0.1.0.1
- AesonBson-0.4.0
- cache-0.1.3.0
packages:
- '.'
- './keycloak-hs'
- './orion-hs'
allow-newer: true
